chef/cookbooks/nova/templates/default/nova.conf.erb

The V1 API is deprecated and since the Horizon dashboard defaults
to V2 as well, it makes more sense to use the same API level
from all services.

Switch to Cinder Volume V2 service

---

chef/cookbooks/nova/libraries/availability_zone.rb
chef/cookbooks/nova/recipes/api.rb
chef/cookbooks/nova/recipes/availability_zones.rb
chef/cookbooks/nova/recipes/compute.rb
chef/cookbooks/nova/recipes/config.rb

Instead of doing N calls (where N is the number of compute nodes) on the
controller, which doesn't scale (it can be slow and make chef-client
take a long time to complete), we just do one call on each compute node.
Except for Hyper-V compute nodes, that are still handled by the
controller due to the fact that they don't have the small utility.

Move calls to crowbar-nova-set-availability-zone to compute nodes

---

chef/roles/nova-multi-compute-hyperv.rb

This allows us to not know about all the hyperv recipes, and the right
order to use.
This depends on https://github.com/crowbar/barclamp-hyperv-compute/pull/22

Use new do_all recipe to install hyperv bits

---

chef/cookbooks/nova/files/default/crowbar-nova-set-availability-zone
chef/cookbooks/nova/recipes/compute.rb

When all hosts are rebooted, there is a race on which one
comes up first. Chances are high that compute hots, having
less stuff installed, come up first, and then hit an unavailable
controller node. Ignore those failures.

Avoid crowbar_join failing on Nova API being unavailable (bnc#916562)

---

chef/cookbooks/nova/files/default/api-paste.ini
chef/cookbooks/nova/recipes/api.rb

Since commit 06c1c6e removed the api-paste.ini template from chef,
systems which already had it installed by chef would keep the old
version because it was modified outside of rpm. But these files
contained the auth_token middleware configuration which would conflict
with the one from nova.conf.
This commit fixes that problem by making sure to overwrite api-paste.ini
with a vanilla file from the git repository (current stable/icehouse).

[stoney] Ensure that api-paste.ini does not contain the auth_token

---

chef/cookbooks/nova/templates/default/nova.conf.erb

auth_uri needs to point to the public endpoint and identity_uri
to the internal node. Use keystone_settings for transparent HA
support.

Fix auth_uri/identity_uri

---

chef/cookbooks/nova/recipes/compute.rb
chef/cookbooks/nova/recipes/config.rb

When using external Ceph, we still need to setup
the Ceph integration in KVM and nova-compute.

Install Ceph integration on compute nodes if needed

---

chef/cookbooks/nova/recipes/config.rb

networking_plugin and networking_mode are not used in the nova.conf.erb
template so remove the variables. networking_mode was anyway no longer
available due to barclamp-neutron changes.

Remove unused variables

---

chef/cookbooks/nova/templates/default/nova.conf.erb

The only reason we were not doing this before is that neutron didn't
support it, and now it does.

Use SSL for nova-metadata when SSL is enabled

---

crowbar_framework/app/models/nova_service.rb

This is a requirement for DVR, see slide 4 of
http://fr.slideshare.net/carlbaldwin/dvr-slides

Allocate a public IP for compute host if DVR is enabled

---

crowbar_framework/app/models/nova_service.rb

We were doing giving the controller an IP on os_sdn (which makes no
sense for the nova controller).
Also, vmware compute nodes don't need direct access to networking.

Only allocate IP addresses for neutron on compute nodes

---

chef/roles/nova-multi-compute-hyperv.rb

We split the the setup recipe in the hyperv cookbook in two seperate
recipes do_setup and do_nova to make the basic setup recipe usable for
other cookbooks too.
**Note:** Depends on https://github.com/crowbar/barclamp-hyperv-compute/pull/32

Do not merge yet - Split recipes in nova-compute-hyperv role

---

chef/roles/nova-multi-compute-hyperv.rb

We split the the setup recipe in the hyperv cookbook in two seperate
recipes do_setup and do_nova to make the basic setup recipe usable for
other cookbooks too.
(cherry picked from commit d1155fdbda57f09a7b493bfc623522651bed8df2)
As Jiri is in Vancouver I take over from here: https://github.com/crowbar/barclamp-nova/pull/453
where this has already been reviewed.

Split recipes in nova-compute-hyperv role

---

chef/cookbooks/nova/recipes/ceph.rb

The first line may start with "UUID" or " UUID". We were not
supporting the latter...

ceph: Fix parsing of "virsh secret-list" header

---

chef/cookbooks/nova/recipes/ceph.rb

Backport of https://github.com/crowbar/barclamp-nova/pull/458
The first line may start with "UUID" or " UUID". We were not supporting
the latter...
https://bugzilla.suse.com/show_bug.cgi?id=931284
(cherry picked from commit c9c66954b3574f306ef28baeb0e48922be50e4c9)

[tex] ceph: Fix parsing of "virsh secret-list" header (bsc#931284)

---

chef/cookbooks/nova/templates/default/nova.conf.erb

Quite confusingly, the 2.1 API is disabled by default and only enabled
when this is in nova.conf:
[osapi_v3]
enabled=true
Since we configure the computev21 endpoint unconditionally, also enable
the API.
Fix found by Roberto Sassu <rsassu@suse.com>
https://bugzilla.suse.com/show_bug.cgi?id=934225

Enable the 2.1 API (bsc#934225)

---

chef/cookbooks/nova/templates/default/nova.conf.erb

Quite confusingly, the 2.1 API is disabled by default and only enabled
when this is in nova.conf:
[osapi_v3]
enabled=true
Since we configure the computev21 endpoint unconditionally, also enable
the API.
Fix found by Roberto Sassu <rsassu@suse.com>
https://bugzilla.suse.com/show_bug.cgi?id=934225
(cherry picked from commit 7dc1fba0a24282a573e198ef50ee177c76a86f7c)

[tex] Enable the 2.1 API (bsc#934225)

---

chef/cookbooks/nova/metadata.rb

Needed if the cookbook is used without the crowbar
framework. I.e. usingthe cookbook as berkshelf dependency.
Also update maintainer email address.

Set cookbook name in metadata

---

crowbar_framework/app/views/barclamp/nova/_edit_attributes.html.haml

otherwise the password is not hidden during typing.

Mark xCat password field as being a password field

---

crowbar_framework/app/models/nova_service.rb

Network notes don't need a public IP allocated,
but they need an interface in the VLAN for nova_floating enabled.

Make nova_floating independent of public network

---

chef/cookbooks/nova/templates/default/nova.conf.erb

It was referring to volumev2:cinder:internalURL, but should be
volumev2:cinderv2:internalURL (as that's what is registered in the
cinder cookbook).

Fix catalog_info setting for cinder in nova.conf

---

chef/cookbooks/nova/recipes/controller_ha.rb

Nova HA resources can take over 1 minute to be set up, as seen by
mkcloud failures in ci.suse.de Jenkins.
https://bugzilla.suse.com/show_bug.cgi?id=935462

increase timeout for synchronization of HA resources (bsc#935462)

---

chef/cookbooks/nova/recipes/controller_ha.rb

(backport of #478 to tex)
Nova HA resources can take over 1 minute to be set up, as seen by
mkcloud failures in ci.suse.de Jenkins.
https://bugzilla.suse.com/show_bug.cgi?id=935462
(cherry picked from commit f04bd35ef94822f8e229e6cfb5219a16f1d92cb9)

[tex] increase timeout for synchronization of HA resources (bsc#935462)

---

chef/cookbooks/nova/recipes/controller_ha.rb

increase timeout for synchronization of HA resources (bsc#935462)
Nova HA resources can take over 1 minute to be set up, as seen by
mkcloud failures in ci.suse.de Jenkins.
https://bugzilla.suse.com/show_bug.cgi?id=935462
(cherry picked from commit f04bd35ef94822f8e229e6cfb5219a16f1d92cb9)

[stoney] increase timeout for synchronization of HA resources (bsc#935462)

---

chef/cookbooks/nova/recipes/controller_ha.rb

Backport from https://github.com/crowbar/crowbar-openstack/pull/8

nova: Correctly configure haproxy for metadata when ssl is on

---

chef/cookbooks/nova/recipes/config.rb
chef/cookbooks/nova/templates/default/nova.conf.erb
chef/data_bags/crowbar/bc-template-nova.json
chef/data_bags/crowbar/bc-template-nova.schema
chef/data_bags/crowbar/migrate/nova/024_add_configdrive.rb

This is useful in environments where the dhcp-agent is
disabled, which means there is no neutron/nova metadata proxy
available.
Backport of https://github.com/crowbar/crowbar-openstack/pull/17

Add option to enforce use of config drive (bsc#943166)
